#### Sr. Engineer: Dhruv Singh <br> Course Name: EDHEC Portfolio Optimization <br> Lesson Name: Deviations from Normality <br> Date Updated: 01/09/2022

# Deviations from Normality

In [2]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import edhec_risk_kit_105 as erk
hfi = erk.get_hfi_returns()
hfi.head()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


QQQ       IWF       VOO       SPY
Date                                           
2010-11 -0.001725  0.011319 -0.001108  0.000000
2010-12  0.045498  0.050642  0.064337  0.061271
2011-01  0.028278  0.024275  0.022234  0.023300
2011-02  0.031607  0.034271  0.034664  0.034737
2011-03 -0.005885 -0.003132 -0.004434 -0.004206

## Skewness

In [3]:
pd.concat([hfi.mean(), hfi.median(), hfi.mean()>hfi.median()], axis=1)

0         1      2
QQQ  0.016220  0.019649  False
IWF  0.013813  0.016816  False
VOO  0.011136  0.014489  False
SPY  0.011091  0.014533  False

### Skewness Function

In [4]:
def skewness(r):
    """
    Alternative to scipy.stats.skew()
    Computes the skewness of the supplied Series or DataFrame
    Returns a float or a Series
    """
    demeaned_r = r - r.mean()
    # use the population standard deviation, so set dof=0
    sigma_r = r.std(ddof=0)
    exp = (demeaned_r**3).mean()
    return exp/sigma_r**3

In [5]:
skewness(hfi).sort_values()

SPY   -0.359901
VOO   -0.352829
IWF   -0.084573
QQQ   -0.032678
dtype: float64

In [6]:
# Skewness using in-built function
import scipy.stats
scipy.stats.skew(hfi)

array([-0.03267802, -0.08457328, -0.3528292 , -0.35990079])

In [7]:
hfi.shape

(134, 4)

In [8]:
# generating a random normal distribution, to test skewness function
import numpy as np
normal_rets = np.random.normal(0, 0.15, (263, 1))

In [9]:
normal_rets.mean(), normal_rets.std()

(-0.02073313543281509, 0.15549870537123212)

In [10]:
erk.skewness(normal_rets)

0.06861013353318737

# Kurtosis

In [11]:
# note: kurtosis of normal distribution is 3
erk.kurtosis(hfi)

QQQ    3.147320
IWF    3.858249
VOO    4.493910
SPY    4.525521
dtype: float64

In [12]:
# comparing with scipy stats' in-built kurtosis function
scipy.stats.kurtosis(hfi) # these numbers are all lower by 3, bc scipy is returning 'excess' kurtosis

array([0.14732024, 0.85824883, 1.49390987, 1.52552138])

In [13]:
# applying to random normal numbers generated earlier
scipy.stats.kurtosis(normal_rets)

array([-0.06157367])

In [14]:
erk.kurtosis(normal_rets)

2.938426333765754

## Running the Jarque-Bera Test for Normality

In [15]:
scipy.stats.jarque_bera(normal_rets)

Jarque_beraResult(statistic=0.24788536882075957, pvalue=0.8834304737702028)

In [16]:
# checking normality for etf data
scipy.stats.jarque_bera(hfi) # doesn't given p value above 0.01 because test doesn't recognize independence of columns

Jarque_beraResult(statistic=22.490619673926094, pvalue=1.3068447289543705e-05)

In [17]:
# adding nuanced jacque-bera test to function module
# testing on random normal numbers generated
erk.is_normal(normal_rets)

True

In [18]:
# using aggregate method to solve problem
hfi.aggregate(erk.is_normal)

QQQ     True
IWF     True
VOO    False
SPY    False
dtype: bool

In [19]:
import pandas as pd
isinstance(hfi, pd.DataFrame)

True

In [20]:
# again, running test on generated values
erk.is_normal(normal_rets)

True

## Testing ETF returns for Normality

In [24]:
ffme = erk.get_ffme_returns()
erk.skewness(ffme)

QQQ   -0.032678
IWF   -0.084573
VOO   -0.352829
SPY   -0.359901
dtype: float64

In [25]:
erk.kurtosis(ffme)

QQQ    3.147320
IWF    3.858249
VOO    4.493910
SPY    4.525521
dtype: float64

In [26]:
erk.is_normal(ffme)

QQQ     True
IWF     True
VOO    False
SPY    False
dtype: bool